version: '3'
services:
  react:
    build:
      context: ./react-app/
      dockerfile: ../.docker/react/Dockerfile
    volumes:
      - ./react-app:/srv/app:rw,cached
    ports:
      - "3000:3000"

  php:
    build: .docker/php
    volumes:
      - ./app:/app
      - ./.docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - database
    environment:
      TZ: Europe/Sofia

  nginx:
    image: nginx
    ports:
      - '8080:80'
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app:/app
    depends_on:
      - php

  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - ./pg_db:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
